language: java
jdk:
  - oraclejdk8

os:
  - linux

# enable Java 8u45+, see https://github.com/travis-ci/travis-ci/issues/4042
addons:
  apt:
    packages:
      - oracle-java8-installer

# run in container
sudo: false

# use framebuffer for UI
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  global:
    # ENC_PWD
    - secure: "MiZQYDryxMrzPesY0GOiIaqUSZrjP+bpjBpX9YTO+azWQ47O20C/jVQkHwgTOa6DCcrwssqgWYyXm5UAu7R4n0QcMX04oTqeHER6vwndo00jP6KEhd5LzHLx6AslA6dHTbVYQzwXldgYfIeLqGOPRXPB3mx8XAAIqz6x8wbf618="
    # GH_TOKEN
    - secure: "Yvaete6qRW94kFkf3VkaEL+XcrO6gSJLdmJWBexkhR69cNHM+zXph/rEK/gAF4D0KrpGwFvNiaFwlvoEN4OeQZmjEy8r7F6oSVC2SOYKePV3e8MXK7foIX0KcD3x7z3+wQk8Xqi3EMny9KmF+IaqbB5wQzOt68ip4oRg6rSkVA8="

# publish artifacts and Javadoc after a successful build
after_success:
  - travis/publish.sh

before_deploy:
  - export VERSION=$(gradle -q getVersion)
deploy:
  provider: releases
  api_key:
    secure: "lavM9UTjXI3HDETvbeoU1ntwQADUq90Tg2z+SnKdcXg3QFLVWri2+ACSz8ejCwJwJNsPxtW6vRhsjHLl5l0HCZ9vHDDXdOv9A94czLzYvSM4m3UmmO9KdjkETCZkg+t6hqm0K0yW3Pye3yEnVd/LbWPK2LzvgCqwp3CfqkC1aZE="
  file_glob: true
  file:
    - "build/libs/wellbehavedfx-${VERSION}.jar"
    - "build/libs/wellbehavedfx-${VERSION}-javadoc.jar"
    - "build/libs/wellbehavedfx-${VERSION}-sources.jar"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: TomasMikula/WellBehavedFX
