language: java
jdk:
  - oraclejdk8

os:
  - linux

# run in container
sudo: false

# use framebuffer for UI
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# add Sonatype credentials
env:
  global:
    - secure: "MiZQYDryxMrzPesY0GOiIaqUSZrjP+bpjBpX9YTO+azWQ47O20C/jVQkHwgTOa6DCcrwssqgWYyXm5UAu7R4n0QcMX04oTqeHER6vwndo00jP6KEhd5LzHLx6AslA6dHTbVYQzwXldgYfIeLqGOPRXPB3mx8XAAIqz6x8wbf618="
    - secure: "Yvaete6qRW94kFkf3VkaEL+XcrO6gSJLdmJWBexkhR69cNHM+zXph/rEK/gAF4D0KrpGwFvNiaFwlvoEN4OeQZmjEy8r7F6oSVC2SOYKePV3e8MXK7foIX0KcD3x7z3+wQk8Xqi3EMny9KmF+IaqbB5wQzOt68ip4oRg6rSkVA8="

# publish artifacts and Javadoc after a successful build
after_success:
  - travis/publish.sh
