language: java
jdk:
  - oraclejdk8

os:
  - linux

# run in container
sudo: false

# use framebuffer for UI
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# add Sonatype credentials
env:
  global:
    - secure: "MiZQYDryxMrzPesY0GOiIaqUSZrjP+bpjBpX9YTO+azWQ47O20C/jVQkHwgTOa6DCcrwssqgWYyXm5UAu7R4n0QcMX04oTqeHER6vwndo00jP6KEhd5LzHLx6AslA6dHTbVYQzwXldgYfIeLqGOPRXPB3mx8XAAIqz6x8wbf618="

# publish artifacts after a successful build
after_success:
  - travis/initiate-publish.sh
